### ISSUE TITLE
Run ESP32-S2 CPU on max Frequency

### ISSUE THREAD

**Issue by Tysonpower** [Othernet-Project/Dreamcatcher#13]
I noticed that the CPU is set to run at only 160mhz instead of 240mhz, to minimize Packet loss while serving the Webserver etc. running it on max Frequency would be better i think.

See sdkonfig / config menu in idf.py:

```
# CONFIG_ESP32S2_DEFAULT_CPU_FREQ_80 is not set
CONFIG_ESP32S2_DEFAULT_CPU_FREQ_160=y
# CONFIG_ESP32S2_DEFAULT_CPU_FREQ_240 is not set
CONFIG_ESP32S2_DEFAULT_CPU_FREQ_MHZ=160
```

**Comment by chegewara** [comment]
Did you see CPU high utilization so far?
On S2 160MHz is the standard freq, according to specs, and 240MHz is overclocked. Im not saying it is bad idea, just asking if it is necessary.

**Comment by caveman99** [comment]
I set up a 'mock' DC4 to work a bit on the User Interface and noticed a few thingsd, among those the lack of CPU power. The ESP-S2 is at the moment not capable of processing a 'news' folder of a few broadcast days (i copied the files over from the DC3 to the SD card). Apart from needing to build in pagination to the browser the DC4 can not process any other requests during his grinding. I'm seeing the same packet loss/timeouts @Tysonpower mentioned when doing anything but idling. And this Mock receiver is not even processing packets.

Setup: ESP32S2 WROVER Module on Saola-1R board with SD reader connected via breakout. Neither LORA nor DISEQC chip are hooked up.

Incidentally i couldn't get the code running on a 'stock' ESP32 dual core module. Just produces a bootloop.

**Comment by chegewara** [comment]
The code has not been tested with old esp32 recently, since i am testing it on pre-production devices.

So far i did not have the issue with sd card and file system other than opening arabic news, but such news will be removed soon.
The problem is not with CPU speed, but with small wifi buffers. Sadly we cant make them bigger, because we are just short on memory. Of course i dont see the problem to increase CPU freq to 240MHz, but currently it is the smallest issue.

**Comment by chegewara** [comment]
You can see working DC4 in EU on this website (not always active thou):
http://dc4.esp32.eu.org
